title: RSS-To-Email
description: > # this means to ignore newlines until "baseurl:"
  Turn your RSS feed into a beautiful email newsletter
baseurl: ""
url: "https://email.pcto.co"
github: "https://github.com/portable-cto/rss-to-email"
twitter:
  username: portablecto
  card: summary
logo: /assets/images/logo.png
plugins:
  - jekyll-seo-tag
